# Generated by Django 4.1 on 2024-11-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_comment_news_commen_created_cac50c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
